Make sure to have wit update within the repo

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -28,6 +28,14 @@ jobs:
         run: |
           npm install
 
+      - name: WIT update code quality
+        working-directory: ./golem-ts-sdk
+        run: |
+          npm run wit-update || (
+            echo "Failed to update WIT"
+            exit 1
+          )          
+
       - name: Check code quality
         working-directory: ./golem-ts-sdk
         run: |
